const SAMPLE_PROBLEM = [
  "Owl",
  "Bumblebee",
  "Giraffe",
  "Horse",
  "Squirrel",
  "Swimming",
  "Swimming Pool",
  "Brushing Teeth",
  "Building a Sandcastle",
  "Driving a Car",
  "Dancing",
  "Dating",
  "Opening a Gift",
  "Throwing a football",
  "Washing hair",
  "Buckling a belt",
  "Changing a diaper",
  "Coughing",
  "Sneezing",
  "Going on a picnic",
  "Skateboarding",
  "Spaghetti",
  "Bubblegum",
  "Boba Milk Tea",
  "Eiffel Tower",
  "Seattle Space Needle",
  "Statue of Liberty",
  "Grand Canyon",
  "Frozen",
  "Spiderman",
  "The Lion King",
  "Toy Story",
  "Community",
  "Volunteer",
  "Programming",
  "Covid",
  "Birthday",
  "President",
  "Measure",
  "Judge",
  "Marry",
  "Trampoline",
  "Michael Jackson",
  "Taylor Swift",
  "Britney Spears",
  "Elvis",
  "Hockey",
  "Cheerleading",
  "Croquet",
  "Doctor",
  "Beauty queen",
  "Firefighter", 
  "Santa Claus", 
]; 

export default SAMPLE_PROBLEM;
    
